"""empty message

Revision ID: db29407bb62e
Revises: 971d735d027f
Create Date: 2024-01-04 09:36:13.144518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db29407bb62e'
down_revision = '971d735d027f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeoff',
    sa.Column('timeoff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timeoff', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('dayoftheweek', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('unitoftime', sa.String(length=120), nullable=False),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('timeoff_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeoff')
    # ### end Alembic commands ###
